version: '3.3'
services:
  backend:
    image: node:16-alpine
    working_dir: /usr/src/app
    command: sh -c "npm run sample"
    volumes:
      - ./.:/usr/src/app
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: password
      POSTGRES_DB: example
    # command: postgres -c max_locks_per_transaction=1000
    ports:
      - 5432:5432
    expose:
      - 5432
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
